include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, lib/generated/**.g.dart]

linter:
  rules:
  - always_use_package_imports
  - always_put_control_body_on_new_line
  - lines_longer_than_80_chars
  - avoid_multiple_declarations_per_line
  - prefer_const_constructors
  - prefer_single_quotes